server {
    listen 80;
    server_name dev.oecher-singsang.de www.oecher-singsang.de oecher-singsang.de;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Permissions-Policy "encrypted-media=(self \"https://w.soundcloud.com\")" always;
        try_files $uri $uri/ /index.html;
    }
}
